# This compose file is intended to match the kubernetes composition as close as possible.
services:
  # Load Balancer (Entry Point)
  local.zthunworks.com:
    image: zthun/works.proxy:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./packages/stacks.proxy/conf.d:/etc/nginx/conf.d
    depends_on:
      - zthunworks-application-pokedexii-web
      - zthunworks-application-fashion-web
  # Applications
  zthunworks-application-fashion-web:
    image: zthun/fashion-web:latest
  zthunworks-application-pokedexii-web:
    image: zthun/pokedex-web:latest
