# This compose file is intended to match the kubernetes composition as close as possible.
services:
  # Load Balancer (Entry Point)
  local.zthunworks.com:
    image: zthun/helpful-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.config:/.config
    depends_on:
      - zthunworks-application-cirque-web
      - zthunworks-application-clocks-web
      - zthunworks-application-dalmart-web
      - zthunworks-application-fashion-web
      - zthunworks-application-helpful-web
      - zthunworks-application-janitor-web
      - zthunworks-application-lumberjacky-web
      - zthunworks-application-pokedexii-web
      - zthunworks-application-pokedexii-api
      - zthunworks-application-webigail-web
      - zthunworks-application-works-web
      - zthunworks-application-works-api
  # Applications
  zthunworks-application-cirque-web:
    image: zthun/cirque-web
  zthunworks-application-clocks-web:
    image: zthun/clocks-web
  zthunworks-application-dalmart-web:
    image: zthun/dalmart-web
  zthunworks-application-fashion-web:
    image: zthun/fashion-web
  zthunworks-application-helpful-web:
    image: zthun/helpful-web
  zthunworks-application-janitor-web:
    image: zthun/janitor-web
  zthunworks-application-lumberjacky-web:
    image: zthun/lumberjacky-web
  zthunworks-application-pokedexii-web:
    image: zthun/pokedex-web
  zthunworks-application-pokedexii-api:
    image: zthun/pokedex-api
    depends_on:
      - zthunworks-mongo
    environment:
      - DATABASE_URL=mongodb://zthunworks-mongo
  zthunworks-application-webigail-web:
    image: zthun/webigail-web
  zthunworks-application-works-web:
    image: zthun/works-web
  zthunworks-application-works-api:
    image: zthun/works-api
  zthunworks-mongo:
    image: mongo:5.0
    volumes:
      - stacks-mongo-data:/data/db
  zthunworks-mongo-express:
    image: mongo-express:0.54
    ports:
      - 8081:8081
    depends_on:
      - zthunworks-mongo
    environment:
      - ME_CONFIG_MONGODB_SERVER=zthunworks-mongo
volumes:
  stacks-mongo-data:
