kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Chart.Name }}-deployments-application-pokedexii-api
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-pods-application-pokedexii-api
  template:
    metadata:
      name: {{ .Chart.Name }}-pods-application-pokedexii-api
      labels:
        app: {{ .Chart.Name }}-pods-application-pokedexii-api
    spec:
      containers:
        - name: {{ .Chart.Name }}-pods-application-pokedexii-api
          image: {{ .Values.applications.pokedexii.api }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secrets-db-urls
                  key: database-pokedexii-url