apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    acme.cert-manager.io/http01-edit-in-place: 'true'
    kubernetes.io/ingress.class: 'nginx'
    cert-manager.io/issuer: '{{ .Chart.Name }}-cert-issuer'
spec:
  tls:
    - hosts:
      - pokedexxi.{{ .Values.domain }}
      - fashion.{{ .Values.domain }}
      secretName: {{ .Chart.Name }}-tls
  rules:
    - host: pokedexxi.{{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}-services-application-pokedexxi-web
                port:
                  number: 80
    - host: fashion.{{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}-services-application-fashion-web
                port:
                  number: 80