kind: Secret
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-secrets-db-urls
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  database-pokedexii-url: {{ .Values.database.pokedexii }}
